spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: delivery
    password: delivery
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: delivery-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false
    listener:
      ack-mode: RECORD
    admin:
      fail-fast: false

app:
  topics:
    orderCanceled: order.canceled # Consumed
    kitchenPrepared: kitchen.prepared # Consumed
    deliveryAssigned: delivery.assigned # Produced
    deliveryCompleted: delivery.completed # Produced
