spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:h2:mem:delivery;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: delivery-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false
    listener:
      ack-mode: RECORD

app:
  topics:
    orderCreated: order.created
    orderCanceled: order.canceled
    paymentAuthorized: payment.authorized
    paymentFailed: payment.failed
    kitchenAccepted: kitchen.accepted
    kitchenPrepared: kitchen.prepared
    deliveryAssigned: delivery.assigned
    deliveryCompleted: delivery.completed
